### ISSUE TITLE
🎨 Website header

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-website#1]
#  Create the website header
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a header I can use to navigate the website.

### Description

Your task is to add the website header as described below.

The content of this header will include:

```
1. "Elewa" logo on the left
2. A transparent background 
3. Black text in correct font 
4. Contact button on the right
```

The header looks as follows:

![image](https://github.com/italanta/elewa-website/assets/3729474/a53fa909-0ac4-42b8-84e3-a9348fcc4604)

 **_TODO_** Logo Url -> https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690297/elewa-group-website/Icons/SVG/_Logo/Logo_White_arvoyx.svg

The header needs to be absolute and of higher z-index so that it appears on top of the page banner.

Full design reference: https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/

The container adapts naturally to the following screen widths:

Device | Screen width | Container width
-- | -- | --
Large Screens (Desktops and Laptops) | 1440px | 1200px
Tablets | 768px | 728px
Mobiles | 360px | 320px

<img width="1153" alt="image" src="https://github.com/italanta/elewa-website/assets/3729474/e8ffe287-2282-4a9e-87df-898426116e54">

### Technical Analysis

- Create an angular package in libs/elements/layout/header. Name the module AppHeaderModule
- Create a header component inside a components folder of the package above.
- Export the header in the package 
- Use labels to make the header available in two languages

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The header adapts naturally to different screen widths
3. The header can change language

**Comment by joanne-cmd** [comment]
working on this issue

**Comment by Okellothomas** [comment]
Working on this issue with Elvis Rono, Martin Ntwiga

**Comment by dennis-mburu** [comment]
Working on this issue

**Comment by KaranjaK** [comment]
Working on this Issue

**Comment by stephenonchieku1** [comment]
working on this Issue

**Comment by stephenonchieku1** [comment]
@LemmyMwaura  the  logo url provided belongs to elewa group

**Comment by philipNgungi037** [comment]
Working on this issue
