### ISSUE TITLE
🎨  Home Page Educational Section Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#10]
#  Create the home Page "Educational Solution" section

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a section that shows an Overview section that describes what Elewa does as shown in the image below

### Description

Design:

![educational section](https://github.com/italanta/elewa-website/assets/20738858/3904b373-e214-4ee5-a2e8-5db2418b9d8c)

![Educational section2](https://github.com/italanta/elewa-website/assets/20738858/1361dc86-2930-4dd0-bd34-20cd00ae3d9a)

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528
```
### Technical Analysis

This feature can be found in libs/pages/home inside the components folder. The name of the component is education-section

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS fGrid
- [ ] The design is responsive for screen, tablet and phone

**Comment by JosephWamiti1178** [comment]
Working on this. I am Joseph Mugo

**Comment by JosephWamiti1178** [comment]
Working on this with John Vundi

**Comment by LemmyMwaura** [comment]
@JosephWamiti1178 kindly pick another issue that's not marked as in-design. This specific issue be updated.

**Comment by JosephWamiti1178** [comment]
Thanks. Lemmy

**Comment by LemmyMwaura** [comment]
This issue hasn't been composed into different parts to make it easier to achieve this exact design spec

**Comment by Alexotieno1717** [comment]
working on this
