### ISSUE TITLE
🎨 Create Reusable News Item Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#11]
#  A reusable News Item component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable news item component I can use to present a news item.
I want a good experience on web and phone.

### Description

Design:

![Reusable News-Item Component](https://github.com/italanta/elewa-website/assets/20738858/ec3144f3-a66d-4f8b-9ab9-7ff46c1fbf97)

[Link to full design](https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)

### Technical Analysis

The news component should be placed in the library `libs/elements/cards` (cards is a module)

The module is named "CardsModule" 

It exports the elewa-news-item-card component, for other modules to import. The component name is elewa-news-item-card.

The component accepts an Angular input of type:

```typeScript
interface NewsItem {
  title: string
  description: string
  buttonText: string
}
```

The type/model should be stored in `libs/models/schema/ui/cards` (cards is a module/library). The name of the file containing the interface is news-item.interface.ts and it's exported by its parent module above.

### Data

Mock news items are defined for the component and placed in data/sections under the file name highlighted-news.data.ts.
The file exports a NewsItem[] with the name "__highlightedNews".

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/layout/cards` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/schema/ui/cards` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by PenugondaJayanthi123** [comment]
Hello @LemmyMwaura, Can you assign this issue to me?

**Comment by MarkBrianK** [comment]
Working on this

**Comment by McRonaah** [comment]
LemmyMwaura Kindly check on this CardsModule is not found in the schema

**Comment by LemmyMwaura** [comment]
@McRonaah Yes, that's something you'll have to create using nx to and then add the types to it.

**Comment by jrosseel** [comment]
@PenugondaJayanthi123 @McRonaah @MarkBrianK , please take note of the updated design spec
