### ISSUE TITLE
🎨  Create a reusable team member component

### ISSUE THREAD

**Issue by AnnaL001** [italanta/elewa-website#124]
#  Create a reusable team member component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a component I can reuse throughout the site to display team members in a carousel

### Description

This component displays a team member as shown in the design.

<img width="209" alt="member_item" src="https://github.com/italanta/elewa-website/assets/43697008/9a13cfd1-f320-4142-9abf-a5ff2b53f9df">

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/
```
### Technical Analysis

This component will be created in `libs/elements/cards` (cards is a module)

The component will be called team-member-card

The component accepts one Angular input of type:

```typeScript
interface TeamMember {
  fullName: string
  imgSrc: string
}
```
The type/model should be stored in `libs/models/ui/cards` (cards is a module/library)

The name of the file containing the interface is team-member.interface.ts and it's exported by its parent module above.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/cards` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/ui/cards` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone.
- [ ] The image renders fast and has multiple srcsets.

**Comment by philipNgungi037** [comment]
Working on this.

**Comment by sammuthaiga** [comment]
Working on this
