### ISSUE TITLE
🎨 Create Home Page News Section Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#13]
#  🎨 Create the Home Page News Section Component
---

#### Note: This issue is dependent on #11 , please complete that before you continue.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a section that displays all news- items(blogs) that I have on my homepage.

![NewsPage](https://github.com/italanta/elewa-website/assets/20738858/16a5409b-636c-4721-a576-a59d0930aa9e)

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```
### Technical Analysis

This component will be created in libs/pages/home/components, The name of the component will be news-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The design is responsive for screen, tablet and phone
6. The image renders fast and has multiple srcsets

**Comment by njugunaemilly** [comment]
Working on it @gikonyo-otieno

**Comment by JosephWamiti1178** [comment]
Working on this

**Comment by kevinkkimutai** [comment]
working on this

**Comment by Iank-code** [comment]
Working on it

**Comment by kiplangat01** [comment]
working on this
