### ISSUE TITLE
🎨 App Layout - Create Website Footer

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#135]
#  Create the website footer
---
Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)
---

### Summary

As a user I want a simple footer that displays my information in a structured way.
Another component can be injected into the footer to highlight a certain action per page

### Description

Currently the website page has no footer. Your job is to add one. The footer needs to appear well on web and mobile:

Web:

![dynamic footer](https://github.com/italanta/elewa-website/assets/20738858/2b793713-5c98-4a46-b44c-d2e178b31cf6)

Mobile:

![dynamic footer mobile](https://github.com/italanta/elewa-website/assets/20738858/42969dfb-ec0e-4199-a755-15ad8d02dd0f)

NB: The mobile design is for a different website, ours should look exactly the same apart from the textual content itself

---
Link to full design:

```
https://xd.adobe.com/view/30f592fb-2ceb-4ea9-a6b9-2aee6239a957-65a6/screen/9ce6f3d4-3ff5-4c36-86f0-bf3a67e02b13
```

### Technical Analysis

Create a layout package in libs/elements/layout/footer

Create a footer component inside a components folder of the package above.
Add a module and export the component.

The footer has a dynamic component which can change from page to page, as illustrated below:

![dynamic footer transclution](https://github.com/italanta/elewa-website/assets/20738858/d54496d4-bc3d-433b-9181-09f61d92a455)

Use simple content projection/transclusion for this through the `<ng-content></ng-content>` element

https://angular.io/guide/content-projection

#### Social media links

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690295/elewa-group-website/Icons/SVG/_Social/instagram_x8ujcq.svg

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/Icons/SVG/_Social/linkedin_x8smhm.svg

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/Icons/SVG/_Social/facebook_lhhwk2.svg

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/elements/layout/footer package, unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] The component allows for a transclusive element that is centered using CSS

**Comment by sainamercy** [comment]
working on this

**Comment by kevinkkimutai** [comment]
working on this

**Comment by KaranjaK** [comment]
I am working on this issue.

**Comment by LemmyMwaura** [comment]
Completed in #144
