### ISSUE TITLE
🎨 Create Reusable Project Item Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#14]
#  Create reusable project item component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a component I can reuse throughout the site to display project items in a carousel

### Description

This component displays a project item as shown in the design.

![Project-item](https://github.com/italanta/elewa-website/assets/20738858/bcfca354-4480-4d1f-a618-4859e7945f87)

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/
```
### Technical Analysis

This component will be created in `libs/elements/cards` (cards is a module)

The component will be called elewa-project-item-card

The component accepts one Angular input of type:

```typeScript
interface ProjectItem {
  title: string
  description: string
  tag: string
  imgSrc: string
}
```
The type/model should be stored in `libs/models/ui/cards` (cards is a module/library)

The name of the file containing the interface is project-item.interface.ts and it's exported by its parent module above.

### Data

Mock projects are defined for the component and placed in data/sections under the file name highlighted-projects.data.ts.
The file exports a Projects[] with the name "__highlightedProjects".

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/cards` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/ui/cards` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone.
- [ ] The image renders fast and has multiple srcsets.

**Comment by sammuthaiga** [comment]
Working on this

**Comment by Kelvin-Wepo** [comment]
working on this one

**Comment by jrosseel** [comment]
@sammuthaiga  @Kelvin-Wepo , please note the updated requirements

**Comment by joanne-cmd** [comment]
working on this

**Comment by sophie-ndalo** [comment]
working on this issue with @ochieng23
