### ISSUE TITLE
🎨 Create Reusable Pricing List Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#141]
## User stories

A user I want a Reusable Pricing List Component.

#### Note: This issue is dependent on #81 , please complete that before you continue.

---

### Summary

As a developer, I want a reusable pricing list card component I can use to render the billing list for the unique service that I offer. The component is reusable as it will be needed on different pages, I want a good experience on the web and phone. 

### Description

Design:

![pricing cards](https://github.com/italanta/elewa-website/assets/20738858/209748e2-f1a9-431e-b9d8-6898790e1cdd)

[Link to full design](https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)

### Technical Analysis

The reusable price list component should be placed in the library `libs/elements/cards` (cards is a module that already exists) in the components folder. The component name is elewa-price-list. It's exported by it's parent module above. It reuses the component created in #81.

The component accepts an Angular input of type (already in the codebase):

```typeScript
 priceItem []
```

### Data

Mock news items are defined for the component and placed in data/sections (already in the codebase) under the file name pricing-list.data.ts.
The index file exports a priceItem[] with the name "__highlightedPricingList".

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/cards` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by Mutagah** [comment]
@LemmyMwaura , Should the component **elewa-price-list,** be under `libs/elements/cards` as specified in the technical analysis or should it be under `libs/elements/layout/cards` as specified in the acceptance criteria?

**Comment by LemmyMwaura** [comment]
It should be under `libs/elements/cards` updating the issue to match this. @Mutagah

**Comment by LemmyMwaura** [comment]
Closed in #197
