### ISSUE TITLE
💄 🎨 Create the booklets page hero section

### ISSUE THREAD

**Issue by AnnaL001** [italanta/elewa-website#15]
#  Create the booklets page hero section 
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a nice hero section on the booklets page that captures my attention and introduces the page content. Reuse the text-content component created in #20, and the reusable slider button in  #24. I want a good experience on the web and phone.

Design:

<img width="1053" alt="booklets_page_hero" src="https://github.com/italanta/elewa-website/assets/43697008/c6d237ca-798c-4d3b-aeda-22cd697b9e46">

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```
 
### Technical Analysis

This feature can be found in libs/features/pages/booklets-page inside a components folder. The component's name is booklets-hero-section.

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the global style.scss
5. The design is responsive for screen, tablet and phone

**Comment by LemmyMwaura** [comment]
Anyone working on this take note of the updated design spec
