### ISSUE TITLE
🎨 Create Projects Carousel

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#16]
#  Create the Projects Carousel Section.
---

#### Note: This issue is dependent on #14, please complete that first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a nice carousel to display all my projects as a list. I should be able to move the carousel and view projects that are not yet in view.

### Description

Design:

![Projects Page Component](https://github.com/italanta/elewa-website/assets/20738858/42a47ab6-07d2-45bc-b36b-3dc98805cbca)

![Corousel2](https://github.com/italanta/elewa-website/assets/20738858/460280f6-94d9-4ccf-af63-52ef5c50f8bb)

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528
```

### Technical Analysis

This feature can be found in libs/elements/carousel
This feature consists out of at least two different components, i.e. a content-card and a carousel list. More components might exist for your determination. The carousel-list component takes a list of projects as input. It should use the component in #14 to display the projects.

### Acceptance Criteria

1. When rendered the component is pixel-perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The main code is isolated to the libs/elements/layout/carousel package. The card is isolated in libs/elements/layout/cards
5. The project interface is defined. No any types are being used anywhere
6. The design is responsive for screen, tablet and phone

**Comment by sainamercy** [comment]
working on this

**Comment by kiplangat01** [comment]
working on this issue

**Comment by jrosseel** [comment]
@sainamercy @kiplangat01 , please take note of the updated spec
