### ISSUE TITLE
💄 🎨 Create the booklets page text and image banner section(side by side)

### ISSUE THREAD

**Issue by AnnaL001** [italanta/elewa-website#17]
#  Create the booklets page text and image banner section(side by side)
---

#### Note: This issue is dependent on #8, please complete that first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

 

---
### Summary

As a user, I want a beautiful-looking section that provides the main content of the bookings page.
I want a good experience on the web and phone. Reuse the component created in #8.

### Description

Design:
<img width="1046" alt="bookings_page_main" src="https://github.com/italanta/elewa-website/assets/43697008/7d605fea-4260-420a-af3c-f292ea7d4335">

Link to full design:

```
https://xd.adobe.com/view/30f592fb-2ceb-4ea9-a6b9-2aee6239a957-65a6/screen/9ce6f3d4-3ff5-4c36-86f0-bf3a67e02b13
```

 

### Technical Analysis

 
This feature can be found in libs/pages/booklets-page module inside a components folder. This feature is a standalone component.
 

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the `libs/features/page/booklets-page` package, unless a justified reason is specified.
5. The design is responsive for screen, tablet and phone

**Comment by KaranjaK** [comment]
I am working on this

**Comment by philipNgungi037** [comment]
Working on this.
