### ISSUE TITLE
🎨 Create Contact Page Form

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#184]
#  Create the contact page form section 
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a nice user-friendly contact form on my Contact page to facilitate easy communication with my users.

Design:

![contact form section](https://github.com/italanta/elewa-website/assets/20738858/c29e56db-743a-44a9-9ed7-fc4ba3684297)

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```
 
### Technical Analysis

This feature can be found in `libs\features\pages\contact-page` inside a components folder. The component's name is contact-page-form-section. Use [Reactive Forms](https://angular.io/guide/reactive-forms) to process user input i.e. add logic to submit the form/collect the user data (don't send it anywhere). 

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the global style.scss
5. The design is responsive for screen, tablet and phone

**Comment by kevinkkimutai** [comment]
working on this
