### ISSUE TITLE
:art: Create an image-container component

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-website#19]
# Create a reusable image container component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a few consistent sets of displaying images.

### Description

As seen on the designs (link below), there are different ways in which we visualise images.

We differentiate the following forms:

<img width="830" alt="image" src="https://github.com/italanta/elewa-website/assets/3729474/d0f0a7bb-c096-4cc1-9ef2-6b355b9052b6">

- **Pill**: The pill is an oval rounded shape with the roundings being on the top and bottom (rounding of each corner is 30% of window height)
- **Stacked**: The stacked cuts out two horizontal pills
- **Window**: A window rounds at the top only (rounding is 30% of height)
- **Card**: A card image only rounds slightly (5 to 10px)

These cutouts are provided by a component called an "image-container".

An "image-container" accepts an input of type "ImageConfig", which has the following properties:

```
1. Title 
2. Image source
3. Visualisation (type ImageVisualisation = Enum { Pill = 0, Stacked = 1, Window = 2, Card = 3 })
4. Max-width (optional)
```

```typeScript
interface ImageConfig {
  title: string
  imageSrc: string
  visualisation: ImageVisualisation
  maxWidth?: string
}

export enum ImageVisualisation {
  Pill = 0,
  stacked = 1,
  Window = 2,
  Card = 3
}
```
The type/model should be stored in `libs/models/schema/ui/images` (images is a module/library)

The name of the file containing the interface is image-config.interface.ts and it's exported by its parent module above.

Your assignment is to implement the component to appear as above.

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```
### Technical Analysis

This component will be created in libs/elements/layout/images

The name of the component will be "elewa-image-container"

Use CSS clipping to visualise the different image forms - https://css-tricks.com/clipping-masking-css/

### Acceptance Criteria

1. When rendered the component is pixel-perfect compared to several of the designs above.
2. The component is clean and does not have more than 80 lines
3. The component accepts rectangular width/height images and uses clipping masks to achieve the desired image shapes
4. The correct types are defined in "model/ui/images"
6. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
7. The code is isolated to the libs/elements/layout/images package, unless a justified reason is specified.
8. The design is responsive and reacts to screens smaller than
9. The image renders fast and has multiple srcsets

**Comment by Leestan360** [comment]
Working on the issue

**Comment by Lekopien** [comment]
Working on it

**Comment by kevinkkimutai** [comment]
working on this

**Comment by NewtonOmbese** [comment]
Working on this @LemmyMwaura

**Comment by Benjah7** [comment]
working on it with @kevinkkimutai valyne306

**Comment by Lawrence137** [comment]
working on this with @Whitneyjoymuchira and @BrianWahungu

**Comment by philipNgungi037** [comment]
Working on this issue.

**Comment by KaranjaK** [comment]
I am working on this.

**Comment by kiplangat01** [comment]
working on this issue

**Comment by Ochieng23** [comment]
working on this

**Comment by erhic** [comment]
I am working on this.
