### ISSUE TITLE
🔥 Remove default Nx template from the site

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#2]
#  Remove default Nx template from the site
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to interact with the elewa website.

### Description

Currently the site contains a default NX template. Remove the template and replace with a simple landing page with black background and white text "Elewa Education".

Current site is as shown below

<img width="1440" alt="Screenshot 2023-02-02 at 11 24 12" src="https://user-images.githubusercontent.com/29625264/216270763-8eb0ccf8-e461-4e54-8c8f-53ee05f2799d.png">

### Technical Analysis

This feature can be found in apps/elewa-group-website

Create a temporary landing page on libs/features/elewa/home

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.

**Comment by kevinkkimutai** [comment]
i am working on this.
