### ISSUE TITLE
🎨 Create Reusable Hero Text Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#20]
#  Create a reusable Text-Section component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable text-section component I can use to render hero section texts i.e title, description and subtitle for the different pages in our app.

I want a good experience on the web and phone.

### Description

Design:

![HeroText1](https://github.com/italanta/elewa-website/assets/20738858/88838297-4a73-4a05-ba99-fb13a5602b7c)

![HeroText2](https://github.com/italanta/elewa-website/assets/20738858/f330da9c-5ffc-4bf7-9272-ac0fc18f4cbb)

[Link to full design](https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)

### Technical Analysis

The text-section component should be placed in the library **libs/elements/layout/texts**

Use the command `nx generate @nrwl/angular:library elements/layout/texts` to create this library. Make sure it's a separate commit. The text component is a reusable component that can be used by e.g. the home page to properly display its hero text items (title, description, subtitle).

The component name is elewa-text-section.

The module is named "TextsModule". It exports the elewa-hero-text-item component, for other modules to import.

The component accepts an Angular input of type:

```typeScript
interface HeroText {
  title: string
  subtitle?: string
  description?: string
}
```
Most of the parameters are optional, and therefore nullable (hence the ?) on the variable. If a variable is not set, its part of text-section is not rendered.

The type/model should be stored in `libs/models/schema/ui/texts` (texts is a module/library). The name of the file containing the interface is hero-text.interface.ts and it's exported by its parent module above.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/layout/texts` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/schema/ui/texts` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by JohnOkari** [comment]
Working on this issue with Justus Kyalo

**Comment by Tracie35** [comment]
I'm working on this

**Comment by joanne-cmd** [comment]
working on this issue

**Comment by Marionwanyama23** [comment]
working on this
