### ISSUE TITLE
🎨 Create Reusable Normal Button Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#23]
#  Create reusable Normal Button component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable normal button component that I can reuse anywhere it's needed across my application.

### Description

**Design**:

![button-1](https://github.com/italanta/elewa-website/assets/20738858/0e2bb686-b077-41fa-b762-bef5fd42e2b8)
![NormalButton](https://github.com/italanta/elewa-website/assets/20738858/5b2bc8fa-20e5-40a0-8065-95cd7a63b995)

[Link to full design](https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)

### Technical Analysis

The button component should be placed in the library **libs/elements/layout/buttons** (buttons is a module/library). Use the command `nx generate @nrwl/angular:library elements/layout/buttons` to create this library. Make sure it's a separate commit.

The normal button component is a reusable component that can be reused across my application. The component name is elewa-normal-button. 

The angular module is named "ButtonsModule". It exports the elewa-normal-button component, for other modules to import.

The component exposes one Angular input of type:

```typeScript
interface ButtonData 
{
  text: string
  
  bgColor?: string; // Background colour
  color?: string; // text color
  
  hoverBgColor?: string;
  hoverColor?: string;
}
```
Most of the parameters are optional, and therefore nullable (hence the ?) on the variable. If the variables are set, the button adopts the correct colours. If not, the default colours are used as per the design spec.

The type/model should be stored in `libs/models/schema/ui/buttons` (buttons is a module/library). The name of the file containing the interface is button.interface.ts and it's exported by its parent module above.

On click, the button exports an output called (click). The click output is an EventEmitter of type void.

### Behaviour

When hovering over the slider, the slider adapts and moves via an animation. The icon at the end moves to the front and the colour changes per design spec. Use SCSS animations for this.

Default, the hover inverts the colours so if the icon is black and the slider is white, the slider becomes black and the icon becomes white.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by danielsind** [comment]
I am working on this

**Comment by jrosseel** [comment]
@danielsind , you have already selected the slider button. Please do one issue at a time

**Comment by Gikonyo-Otieno** [comment]
Working on this with @njugunaemilly

**Comment by Alexotieno1717** [comment]
I am working on this

**Comment by danielsind** [comment]
> @danielsind, you have already selected the slider button. Please do one issue at a time

Can I start working on another issue, once I have pushed the latest changes to the issue I was working on?

**Comment by Whitneyjoymuchira** [comment]
Working on this issue with @BrianWahungu and @Lawrence137

**Comment by jrosseel** [comment]
> > @danielsind, you have already selected the slider button. Please do one issue at a time
> 
> Can I start working on another issue, once I have pushed the latest changes to the issue I was working on?

Sure, if the PR has been raised

**Comment by Evalyne306** [comment]
i am working on this.

**Comment by n-pretorious** [comment]
working on this

**Comment by AlbertPm1** [comment]
working on this

**Comment by Marionwanyama23** [comment]
Working on this

**Comment by kevinkkimutai** [comment]
working on this
