### ISSUE TITLE
🎨 Create Reusable Slider Button Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#24]
#  Create a reusable Slider Button component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

## Summary

As a developer, I want a reusable slider button component that I can reuse anywhere it's needed across my application.

## Description

**Design**:

![slider-button](https://github.com/italanta/elewa-website/assets/20738858/df50db28-69af-460c-bcc5-a5f58165ad70)

![slider-button-2](https://github.com/italanta/elewa-website/assets/20738858/26668aa2-69ea-4de6-b04f-7f44bd2332bc)

[Link to full design](https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)

### Package

The button component should be placed in the library **libs/elements/layout/buttons** (buttons is a module/library)

Use the command `nx generate @nrwl/angular:library elements/layout/buttons` to create this library. Make sure it's a separate commit.

The normal button component is a reusable component that can be reused across my application. The module is named "ButtonsModule". The normal button is being developed in #23. Avoid merge conflicts when creating the package.

The ButtonsModule exports the elewa-normal-button component, for other modules to import.

You are adding a second component to this package, i.e. elewa-slider-button.

### Input and outputs

The component exposes one Angular input of type:

```typeScript
interface SliderButtonData extends ButtonData
{
  text: string;

  bgColour?: string; // Background colour
  color?: string;
  borderColor?: string;
  iconColor?: string;
  iconBackgroundColor?: string;

  hoverBgColour?: string;
  hoverColor?: string;
  hoverBorderColor?: string;
  hoverIconColor?: string;
  hoverIconBackgroundColor?: string;
}
```
Most of the parameters are optional, and therefore nullable (hence the ?) on the variable. If the variables are set, the button adopts the correct colours. If not, the default colours are used as per the design spec.

The type/model should be stored in `libs/models/schema/ui/buttons` (buttons is a module/library) The name of the file containing the interface is slider-button-data.interface.ts and it's exported by its parent module above.

On click, the button exports an output called (click). The click output is an EventEmitter of type void.

### Behaviour

When hovering over the slider, the mouse shows the button is clickable and the slider adapts and moves via an animation. The icon at the end moves to the front and the colour changes per design spec. Use SCSS animations for this.

Default, the hover inverts the colours so if the icon is black and the slider is white, the slider becomes black and the icon becomes white.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/layout/buttons` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/schema/ui/buttons` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by danielsind** [comment]
Working on this

**Comment by jrosseel** [comment]
@danielsind, please note updated spec

**Comment by BrianWahungu** [comment]
Working on this with @whitneyjoymuchira, @lawrence137

**Comment by stephenonchieku1** [comment]
working on this with @Randy

**Comment by randy** [comment]
> working on this with @randy

Just a heads-up, you're tagging the wrong person.

**Comment by Ochieng23** [comment]
Working on this.

**Comment by KaranjaK** [comment]
Working on this
