### ISSUE TITLE
🎨📝 Create Reusable Content-Text Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#27]
#  Create a reusable Content-Text component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I require a versatile text content component that I can easily integrate into the app to display various forms of textual information.

I want a good experience on the web and phone.

### Description

Design:

![Screenshot 2023-08-08 153758](https://github.com/italanta/elewa-website/assets/20738858/d052cb81-4226-48f3-847f-beecda3bd1f1) 

![Screenshot 2023-08-08 153934](https://github.com/italanta/elewa-website/assets/20738858/ba644637-b43b-46ab-bb25-2d9407dd15e1)

Link to full Design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528
```

### Technical Analysis

The text-content component should be placed in the library **libs/elements/layout/texts**

Use the command `nx generate @nrwl/angular:library elements/layout/texts` to create this library. Make sure it's a separate commit. The text component is a reusable component that can be used by other sections across the application.

The component name is elewa-text-content-item.

The module is named "TextsModule". It exports the elewa-text-content-item component, for other modules to import.

The component accepts an Angular input of type:

```typeScript
interface ContentText {
  title: string
  descriptions: string[]
}
```
You should loop through the list of descriptions using the `*ngfor directive` and render them with a space between as shown in the design spec.
The type/model should be stored in `libs/models/schema/ui/texts` (texts is a module/library). The name of the file containing the interface is content-text.interface.ts and it's exported by its parent module above.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/layout/texts` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/schema/ui/texts` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by preston-56** [comment]
on this as well :smile:

**Comment by Wattima** [comment]
working on this

**Comment by philipNgungi037** [comment]
Working on this.

**Comment by Marionwanyama23** [comment]
Working on this.

**Comment by johnVundi** [comment]
Trying this out
