### ISSUE TITLE
🎨 Create Reusable InfoCard Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#28]
#  A reusable InfoCard component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable info card component I can use to present data well.

### Description

Design:
![Card](https://github.com/italanta/elewa-website/assets/20738858/93bfc721-1c4b-4e4a-800c-f80810b1ec68)

Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)
```

### Technical Analysis

The news component should be placed in the library `libs/elements/cards` (cards is a module). The module is named "CardsModule" 

It exports the elewa-info-card component, for other modules to import. 
The component accepts an Angular input of type:

```typeScript
interface InfoCard {
  title: string
  description: string
  icon: string
}
```

The type/model should be stored in `libs/models/schema/ui/cards` (cards is a module/library). The name of the file containing the interface is info-card.interface.ts and it's exported by its parent module above.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/layout/cards` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/schema/ui/cards` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by kiplangat01** [comment]
working on this issue

**Comment by Marionwanyama23** [comment]
Working on this issue #28
