### ISSUE TITLE
🎨 HomePage Partners Section 

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#7]
#  🎨 Create the partner's section on the HomePage
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that shows/lists all our core business partners. Check the full design below for component placement

![partners-section](https://github.com/italanta/elewa-website/assets/20738858/4d0ff186-32ca-4b74-8f64-9ac910e9b41f)

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528/
```
### Technical Analysis

This component will be created in libs/pages/home/components, The name of the component will be partners-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The design is responsive for screen, tablet and phone
6. The image renders fast and has multiple srcsets

**Comment by Lekopien** [comment]
Working on an issue

**Comment by kiplangat01** [comment]
working on this with @Benjah7 and @Evalyne301

**Comment by Evalyne306** [comment]
working on it @Benjah7 @kiplangat01

**Comment by Benjah7** [comment]
Am working on this with @kiplangat01 and @LemmyMwaura Evalyne301

**Comment by jrosseel** [comment]
This issue has been closed as 99% of the work has already been done by myself during the Friday session. Please pick another issue @Lekopien @kiplangat01 @Evalyne306 @Benjah7 

You can review the code on the branch https://github.com/italanta/elewa-website/tree/reference-images 

@LemmyMwaura please note the above

**Comment by LemmyMwaura** [comment]
Closing as completed.
