### ISSUE TITLE
🎨 Create Reusable Image and Text Banner

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#8]
#  Create reusable text and image banner (side by side)
---

#### Note: This issue is dependent on #19 and #27 , please complete that before you continue.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a component I can reuse throughout the site to display images and text side by side.

### Description

This component displays text and images side by side on the site

![text image component](https://github.com/italanta/elewa-website/assets/20738858/bd39dc38-2172-418b-8992-c67890341a20)

![text image component2](https://github.com/italanta/elewa-website/assets/20738858/853b9d5b-09ae-4595-989c-63d7d470181b)

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/
```
### Technical Analysis

This component will be created in `libs/elements/banners` (banners is a module). The component will be called elewa-image-and-text-banner. The component reuses the image-container and is therefore dependant on #19 . The component reuses the title and paragraph component in #27.

The section has an input of the below type to the component that will be passed down to the reusable components in the linked issue:

ImageConfig -> #19 and ContentText -> #27

```typeScript
interface ImageAndText {
  content: ContentText
  image: ImageConfig
  imagePosition: 'left' | 'right'
}
```

### Acceptance Criteria

1. When rendered the component is pixel-perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by MuthonduG** [comment]
working on this

**Comment by Iank-code** [comment]
Working on this

**Comment by KaranjaK** [comment]
I am working on this

**Comment by sammuthaiga** [comment]
Working on this issue.

**Comment by erhic** [comment]
working  on this .

**Comment by philipNgungi037** [comment]
Working on this.
