### ISSUE TITLE
🎨 💄 Create A Reusable Pricing Card Component

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#81]
#  A Reusable Pricing Card Component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable pricing card component I can use to render an individual price card.
I want a good experience on the web and phone.

### Description

Design:

![pricing one](https://github.com/italanta/elewa-website/assets/20738858/ce061822-3a0e-4a6a-aa84-8997f574d307)

![pricing two](https://github.com/italanta/elewa-website/assets/20738858/2ee67864-ecba-4256-a1b9-86bff40598a1)

[Link to full design](https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528)

### Technical Analysis

The reusable price item component should be placed in the library `libs/elements/cards` (cards is a module that already exists)

It exports the elewa-website-price-item-card component, for other modules to import. The component name is elewa-website-price-item-card.

The component accepts an Angular input of type:

```typeScript
interface PriceItem extends PriceItemColors {
  title: string
  amount: number
  subTitle: string
  description: string
  sliderButton: SliderButtonData
}

interface PriceItemColors {
  amountColor: string
  textColor: string
  backgroundColor: string
}
```

The `SliderButtonData` type already exists in the codebase at `libs/models/schema/ui/buttons`.

The type/model should be stored in `libs/models/schema/ui/cards` (cards is a module/library already implemented in the codebase). The name of the file containing the interface is price-item.interface.ts and it's exported by its parent module above.

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the `libs/elements/layout/cards` package unless a justified reason is specified.
- [ ] The model/schema is isolated in the `libs/models/schema/ui/cards` package unless a justified reason is specified.
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by KaranjaK** [comment]
I am working on this.

**Comment by Ochieng23** [comment]
Working on this
