### ISSUE TITLE
✨📝 Create The Content Development Page Module

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#89]
## User stories

As a Developer I need a Page Module where I can create declarations(components, directives...) that will represent the different sections of my content-development page.

---

Quick links: [Summary](#summary) | [Description](#description) | [Template](#template) | [Example](#example) | [Resources](#resources)

---

### Description

As a Developer I need a Page Module where I can create declarations(components, directives...) that will represent the different sections of my content-development page.

### Technical Analysis

The module should be placed in the library `libs/features/pages/content-development` (content-development is a module). The module is named "ContentDevelopmentModule". The module has one component called `content-development-page` found in the `lib/main` folder. For reference check how this has been implemented in the other page modules. 

The route to this should be set in the root routes and it should also have a child routing module that renders the `content-development-page`  component

### Acceptance Criteria

- [ ] The code is isolated to the `libs/features/pages/content-development` package unless a justified reason is specified.
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation

**Comment by Marionwanyama23** [comment]
Working on this issue
