### ISSUE TITLE
🎨 Create Home Page Overview Section

### ISSUE THREAD

**Issue by LemmyMwaura** [italanta/elewa-website#9]
#  Create the home Page "Overview" section

#### Note: This issue is dependent on #19 and #27 , please complete that before you continue.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user, I want a section that shows an Overview section that describes what Elewa does as shown in the image below

### Description

Design:

![Info-section](https://github.com/italanta/elewa-website/assets/20738858/18c19876-5c99-431f-aa68-309c11a27b00)

Link to full design:

```
https://xd.adobe.com/view/b98caf27-6549-49e5-8ed8-c5234788df61-ecdf/screen/cc35e19a-24f2-42ce-8803-ee2942839528
```
### Technical Analysis

This feature can be found in libs/features/pages/home (already created)

### Acceptance Criteria

- [ ] When rendered the component is pixel-perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS flex
- [ ] The design is responsive for screen, tablet and phone

**Comment by McRonaah** [comment]
Working on this?

**Comment by LemmyMwaura** [comment]
Kindy take note of the updated design spec. @McRonaah

**Comment by kevinkkimutai** [comment]
working on this

**Comment by T-erry** [comment]
working on this

**Comment by PerisOduol618** [comment]
woking on this
